### ISSUE TITLE
[ENHANCEMENT]

### ISSUE THREAD

**Issue by Timures** [yanivam/react-svg-worldmap#108]
Hello, Yams Dev

Big thanks for your project react-svg-worldmap, it's very helpfull for people.

I have a little problem when use react-svg-worldmap:

// react-svg-worldmap/lib/src/types.ts

`export interface DataItem {
  country: ISOCode;
  value: number;
}`

If I want to use text to show it in tooltip, 
and writed string in value parameters - logically got error. 
example of my data = { country: 'ke', value: 'Water wells, Farms' },

if I change type of value to string - it's work 
`export interface DataItem {
  country: ISOCode;
  value: string;
}`

So, could u suggest me, please and tell how can I use string in value parameters?

I'm not strong developer, and my proposed solution maybe not good - I think will be good if you add third paramenter like
`export interface DataItem {
  country: ISOCode;
  value: number;
  title: string;
}`

 If this proposed solutions, or changing types is impossible - can I fork project, with string parameter?

Thank you, for your work.

yours respectfully Timures

**Comment by Josh-Cena** [comment]
Hey, the `value` is uniquely used to determine the coloring of the country. If you want to customize the text displayed in the tooltip, you can use the `tooltipTextFunction` prop instead. See https://yanivam.github.io/react-svg-worldmap/examples/localization for an example.
