### ISSUE TITLE
[BUG] no country color when all countries have the same value

### ISSUE THREAD

**Issue by warenbe** [yanivam/react-svg-worldmap#114]
When all the countries have the same value, the world map is blank
it seems that you need to have a "minimum" value with at least 1 country at first render

How to reproduce: 

```
import { WorldMap } from "react-svg-worldmap";
import React, { Component } from 'react';

export default class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      data: []
    }
  }

  addCountry(code) {
    const { data } = this.state;
    this.setState({
      data: [
        ...data,
        { country: code, value: 1 }
      ]
    })
  }

  render() {
    return (
      <div className="App">
        <WorldMap
          color="red"
          title="Top 10 Populous Countries"
          value-suffix="people"
          size="lg"
          data={this.state.data}
          onClickFunction={(country) => { this.addCountry(country.countryCode) }}
        />
      </div>
    );
  }
}
```

now, click a country. it will be white, instead of red, this error will be displayed: 

```
Warning: `NaN` is an invalid value for the `fillOpacity` css style property.
path
Region@http://localhost:3000/static/js/bundle.js:39998:7
g
svg
figure
WorldMap@http://localhost:3000/static/js/bundle.js:40921:7
div
App@http://localhost:3000/main.68d55a7b532f973d3b34.hot-update.js:27:5

```

to solve it, you can simply add a country like: `{country: '', value: 0}`

**Comment by Josh-Cena** [comment]
Hi! This has already been fixed in #109. Unfortunately, @yanivam hasn't got time to release a new version yet. @yanivam Could you take a look? Maybe eventually give me publish access?

**Comment by Josh-Cena** [comment]
@warenbe In the meantime, you can use the [`styleFunction`](https://yanivam.github.io/react-svg-worldmap/examples/custom-style) API to override the default.

**Comment by warenbe** [comment]
Hi
sure i can, and i did
that's more an issue when you discover the library and start to play with it than when using it "for real".

**Comment by Josh-Cena** [comment]
Heh, indeed 😄
