### ISSUE TITLE
[BUG] double click to zoom trigger the onclick event

### ISSUE THREAD

**Issue by warenbe** [yanivam/react-svg-worldmap#115]
Hi
when you enable richinteraction, and then double click somewhere to zoom, it will trigger the onclick if you double clicked on a country
double click should not trigger the onclick event

**Comment by Josh-Cena** [comment]
This is still just playing around, right? 😄

**Comment by warenbe** [comment]
well, yes, i try to do something like "click the country, get information" ;)

**Comment by yanivam** [comment]
Hey @warenbe,
Do you have a quick fix for this? If so feel free to create a PR and we will review it. Sorry about the delay, it has been a very busy time for me lately.
Yams

**Comment by warenbe** [comment]
Hi
no sorry i'm, like you probably, overwhelmed by work, so the project using your tool is in pause currently
but if i find some time to resume it, i'll check it

**Comment by yanivam** [comment]
Zoom is not a feature of this repo
