### ISSUE TITLE
[ENHANCEMENT] Export country list using ESM import

### ISSUE THREAD

**Issue by warenbe** [yanivam/react-svg-worldmap#116]
If you want to create a page with a selector to select countries, instead of clicking on it, it's a good idea to be able to get the list of countries from the library
i took it from source code, but it should be exported
(or i missed something ?)

**Comment by Josh-Cena** [comment]
So you want to get a list like `export countries = ["cn", "us", "de", ...]`?

**Comment by warenbe** [comment]
i'll do as soon as possible

**Comment by warenbe** [comment]
Done.
tells me if i made a mistake. i use github alone, for backup purpose mainly, so i'm not used to use pull requests
