### ISSUE TITLE
[BUG] Did the latest alpha break?

### ISSUE THREAD

**Issue by razzeee** [yanivam/react-svg-worldmap#120]
**Describe the bug** A clear and concise description of what the bug is.

Build is failing with the newest alpha, worked fine with the one before

**To Reproduce** Steps to reproduce the behavior:

Check https://github.com/flathub/website/runs/5752086020?check_suite_focus=true
It's part of https://github.com/flathub/website/pull/84

**Expected behavior** A clear and concise description of what you expected to happen.

Should build fine

**Comment by Josh-Cena** [comment]
Indeed, it's because we don't compile our source to CJS now. While I'll work to fix this, if you exclude node_modules from compilation, can you try excluding this package from that exclude pattern?

**Comment by razzeee** [comment]
I would be happy to wait, unless you want me to test something that way

**Comment by HaruMiyaGi** [comment]
The new version also seems to break for me, I'm getting: `SyntaxError: Cannot use import statement outside a module`, `UnhandledPromiseRejection` errors.

A quick fix is changing `"react-svg-worldmap": "^2.0.0-alpha.0"` to `"react-svg-worldmap": "2.0.0-alpha.0"` if you didn't plan on upgrading versions yet.

**Comment by Josh-Cena** [comment]
Do note that you are encouraged to pin your dependencies for any alpha software. Alphas are meant to "break" between minor versions. Migration to ESM is almost always going to break someone's code, but for us, a client-side library, the impact should be much lower.

@HaruMiyaGi Are you also using Next.js and their default Webpack config? This repo has a Docusaurus site set up and it runs just as usual.

**Comment by jahirfiquitiva** [comment]
@Josh-Cena @yanivam

How can I import the data in `countries.geo.ts` with the latest alpha? I am getting this error in a NextJS app

![Shot 2022-06-14 at 15 09 19@2x](https://user-images.githubusercontent.com/10360816/173679928-1b905ff7-915f-42aa-b44b-9dcdcd3e3040.png)

My code is:
```typescript
import countries from 'react-svg-worldmap/dist/countries.geo';

const data: Data = countries.features.map((country) => {
  return { country: country.I, value: 0 };
});
```

**Comment by yanivam** [comment]
I will investigate this and get back to you within the next week if my workload lightens. Sorry about the delay in this, it has been a busy time for me and I am just getting back into it.
Yams

**Comment by Josh-Cena** [comment]
Hey there, I took a shot in the dark and I hope https://github.com/yanivam/react-svg-worldmap/commit/cce009c4710dabc0de36035487599741b442e1a5 will fix it. Once @yanivam gets to publish another alpha, please kindly let me know if it works. Will be happy to reopen after that. Thanks!

**Comment by razzeee** [comment]
Doesn't seem to help, unless there is something else we would need to change https://github.com/flathub/website/pull/550
