### ISSUE TITLE
Map projection - Kamchatka Peninsula is cut out

### ISSUE THREAD

**Issue by Comi9** [yanivam/react-svg-worldmap#123]
Hi, is there a rationale why a fraction of [Kamchatka Peninsula](https://en.wikipedia.org/wiki/Kamchatka_Peninsula) in Russia is cut out and rendered close to Alaska? Can this be re-arranged?
Thanks!

**Comment by Josh-Cena** [comment]
By "Kamchatka Peninsula", I assume you mean "Chukchi Peninsula"?

I've been long aware of this, but we use an external geodata source, so this would be a bit hard to patch. Definitely on my wishlist, though.

**Comment by Comi9** [comment]
Yeah, my bad, sorry, it's [Chukchi Peninsula](https://en.wikipedia.org/wiki/Chukchi_Peninsula). Figured out that the package is using the Mercator projection.

**Comment by Josh-Cena** [comment]
In a perfect world, we will be able to fix this. I don't think rotating it a bit to reconcile Chukchi with the rest of Russia would break any other country. I don't have much time to work on this project these days, but PRs welcome.

**Comment by Comi9** [comment]
Indeed, it looks like this can be fixed by applying a rotation of [11, 0] ([reference](https://stackoverflow.com/questions/34297690/d3-js-geo-worldmap-merge-russia-shift-small-part-from-the-left-next-to-americ))
`const projection = geoMercator().rotate([-11, 0]);`
