### ISSUE TITLE
[BUG] Statistics map labels do not fit in boxes for RTL languages

### ISSUE THREAD

**Issue by q30a** [yanivam/react-svg-worldmap#125]
**Describe the bug**
Statistics map labels do not fit in boxes for RTL languages

**To Reproduce** Steps to reproduce the behavior:
1. Go to [Flathub beta](https://beta.flathub.org/ar/statistics) - this is RTL language version of statistics map.
2. Hover over countries.
4. See error: labels do not fit in the boxes.

**Expected behavior**
Labels always fit in the boxes regardless of language selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/105132988/168472340-7d490a1b-97d9-469b-bcfe-28c06b722388.png)

**Desktop (please complete the following information):**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:100.0) Gecko/20100101 Firefox/100.0

**Comment by Josh-Cena** [comment]
Please file this in https://github.com/yanivam/react-path-tooltip instead.

**Comment by q30a** [comment]
OK, done. Close this one if needed. Thanks.

**Comment by Josh-Cena** [comment]
btw @q30a a quick fix would be adding `direction: ltr !important;` to the `svg` element.

**Comment by q30a** [comment]
cc @razzeee
