### ISSUE TITLE
[ENHANCEMENT] Convert your data into react-svg-worldmap supported JSON

### ISSUE THREAD

**Issue by deep-gabani** [yanivam/react-svg-worldmap#129]
Problem:
It is mostly the case that the data user have, has country names and values for the respective country. But react-svg-worldmap requires country name in short-name.
It could be a tedious and lengthy process to map them manually.
I'd propose somewhat automation for it - which can automate the country names to short-names (as per this library)

**Comment by Josh-Cena** [comment]
Could you elaborate? Short names (i.e. BCP codes) are standardized and well-accepted, while longer names (i.e. display names) are not. What kind of API do you have in mind to automate this, and how can it be potentially implemented?

**Comment by yanivam** [comment]
Not a planned feature as no work has been done on this since July
