### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by robertoattanasio** [yanivam/react-svg-worldmap#133]
Hello

I've been trying to install the library but I receive lots of errors in console of this kind:

Failed to parse source map from '/[project_url]/node_modules/react-svg-worldmap/src/components/Frame.tsx' file: Error: ENOENT: no such file or directory, open '/[project_url]/node_modules/react-svg-worldmap/src/components/Frame.tsx'.

the problem is other files like:
1. Region.js;
2. TextLabel.js
3. index.tsx

I guess a very basic problem when I install the package. The folder already exists in the node_modules and it seems all the files are there.

**Comment by mteinum** [comment]
Add a file .env in the project with the following content:

`GENERATE_SOURCEMAP=false`

**Comment by jaketoolson** [comment]
I'm having the same issue.

**Comment by yanivam** [comment]
Sorry everyone, I have been away doing my Masters and working full time. I am going to get back to this starting tomorrow. Thanks for your patience. -Yams

**Comment by yanivam** [comment]
Hey @jaketoolson , @david-korecko , @robertoattanasio , and @mteinum . The above error should be resolved in the latest version of the map on npm that I just posted. Can any of y'all check and close this issue? The issue was with the way React was imported. Thanks, Yams

**Comment by yanivam** [comment]
Closing this ticket for now, let me know if the issue persists
