### ISSUE TITLE
[BUG] Ukraine does not include Crimea

### ISSUE THREAD

**Issue by MaxwellKeeble** [yanivam/react-svg-worldmap#137]
Crimea is recognised internationally as part of Ukraine. This map includes it as part of Russia. 

Could this be fixed, and/or at least an alternative countries.geo.ts provided showing the correct boundaries?

**Comment by tao101** [comment]
Yes i support this i think Crimea should be a part of ukraine

**Comment by webdevleo** [comment]
How did it happen that Crimea highlights as part of Russia on the map? This mistake will prevent people to use the package.

**Comment by yanivam** [comment]
I am using data from a NASA open source map from 2018, if you find a better open source one that does not take up a lot of memory space, please let me know. For now, I am closing this ticket as I do not have the time to go find new open source data and deal with cleaning it. -Yams

**Comment by MaxwellKeeble** [comment]
The US has never recognised Crimea as part of Russia, so I am not sure how a NASA map would have shown that. Not providing a link is a bit confusing and concerning. This is a major issue for anyone who would use this map, apart from possibly Russians. 

It is also not correct to mark this as completed when no work has been done. This is not good open source practice, this should be left open for other contributors (and for users of the library to be aware there is a major discrepancy between its data and world consensus).

**Comment by yanivam** [comment]
Reopening until I update data and README to reflect where I got it from

**Comment by yanivam** [comment]
I have added the information about where I got the data from in the README

**Comment by yanivam** [comment]
Crimea is now part of Ukraine
