### ISSUE TITLE
Hong Kong and Singapore are unreachable

### ISSUE THREAD

**Issue by RafaMtz2021** [yanivam/react-svg-worldmap#150]
Although the codes for Hong Kong ("hk") and Singapore ("sg") are sent, they do not appear on the map. Is this a bug?

**Comment by Josh-Cena** [comment]
> the codes for Hong Kong ("hk") and Singapore ("sg") are sent

Not sure what you mean by that. I can see that there's no data for `'HK'` or `'SG'` in our country data: https://github.com/yanivam/react-svg-worldmap/blob/main/lib/src/countries.geo.ts

Unfortunately this data is downloaded from NASA, so there's no way for us to update this ourselves. TBH, Hong Kong and Singapore are so small that they would be literally inaccessible anyway. (Other mini-country/regions are missing as well, like Vatican City and Liechtenstein.)
