### ISSUE TITLE
Property for Worldmap to see all country names per default

### ISSUE THREAD

**Issue by PascalRauprecht** [yanivam/react-svg-worldmap#153]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm No

**Describe the solution you'd like** So far you only see the country names by mouse hovering over them. Would be great to see all of them by default via optional boolean setting for the WorldMap component. Screenshots of the worldmap would be one use case. In screenshots taken you would then see all of the country names. 

**Describe alternatives you've considered** Well, there are not really alternatives.

**Additional context** Great component!

**Comment by Josh-Cena** [comment]
This would very likely be crowded unless there are very few text labels or the map is really large. This might already be achievable via `textLabelFunction`, and I don't think a built-in solution can do significantly better at figuring out where the text labels should go.
