### ISSUE TITLE
[BUG] Crimea is not displayed as a territory of Ukraine

### ISSUE THREAD

**Issue by OrestLue** [yanivam/react-svg-worldmap#154]
Mistake in the mapping of Ukraine's borders
![2024-07-28 1 02 05 PM](https://github.com/user-attachments/assets/ff88224a-3ed4-4af6-a403-d39effd62f35)

**Comment by Josh-Cena** [comment]
I cannot see this issue on our own website: https://yanivam.github.io/react-svg-worldmap/examples/sizing. Make sure you are using the latest version, [2.0.0-alpha.16](https://www.npmjs.com/package/react-svg-worldmap/v/2.0.0-alpha.16).
