### ISSUE TITLE
Better control of color gradient

### ISSUE THREAD

**Issue by billy1234** [yanivam/react-svg-worldmap#40]
On line 122 in your file:
https://github.com/yanivam/react-svg-worldmap/blob/df4914108a1aaaec33ed3f55a42b7a2542fd9f3f/src/WorldMap.tsx#L122

You have 0.2 and 0.6 as constants for opacity, would it be posible to add controls over these numbers or even better an optional function to map colors and opacities, im finding the floor causes missleading color values with countries with a value of 0 still showing some color.

![image](https://user-images.githubusercontent.com/14193480/87275369-488cc880-c521-11ea-95c3-c654270f996a.png)

![image](https://user-images.githubusercontent.com/14193480/87275322-2e52ea80-c521-11ea-9f8a-2baca78b1728.png)

Attached is the same data plotted with matplotlib using a perceptualy uniform color scale.
[matplot lib color scales](https://matplotlib.org/3.1.0/tutorials/colors/colormaps.html)

**Comment by billy1234** [comment]
Something i forgot to add in the original post was control over max /min as it may be usefull aswell. A min like 0 for instance would be quite common.

**Comment by yanivam** [comment]
Hey Billy,

Thanks so much for submitting this issue! I see what you are saying and agree that I should just have a default value and give the user the ability to control the opacity scaling which would significantly improve the map!

I will be adding this to my backlog and will address it asap! Thank you for checking out my code! Look out for version 1.0.25 in which I will try to address this issue as well as another bug that I found in the beta version of the markers.

Appreciate the help, I would love to know what you think when I publish the next version so stay tuned!
Yams

**Comment by yanivam** [comment]
Hey billy,
Thanks for your patience! I have added the styling function as you asked but the minimum and maximum values are calculated by taking the largest and smallest values of the data set. If you want to control the max and min for the opacity, you can just set them to a different value in your function but I added them as inputs for the context so you can use it if you wish. Take a look at the custom example and let me know what you think! If you have any questions or requests let me know. I will leave this open for now in case you have something else to add on.
Thanks again for the request,
Yams

**Comment by billy1234** [comment]
Ive just been playing around with the new changes and it works great, but it has now broken the existing functionality (not sure if its on my end). My code is more or less:

` <WorldMap color="green" 
                            title="Population by Country" 
                            size="lg" 
                            data='thedataarray'} 
                        />
`
and all of the country elements are:
'fill:rgb(221, 221, 221); 
stroke-opacity: 0.2
'

**Comment by yanivam** [comment]
Thanks for checking it out! I'll get on it asap, not sure why it is broken because I essentially used the functionality that I added and made my own function for the default case, so in theory it should work, but I have not set up any automated testing so perhaps you are right and I will take a look and get back to you with a solution.

**Comment by yanivam** [comment]
Hey billy,
You were right! Found the bug and fixed it, let me know if you need anything else/have more ideas for features for me.
Thanks again for your input,
Yams
