### ISSUE TITLE
[ENHANCEMENT] Responsive Width

### ISSUE THREAD

**Issue by peetss** [yanivam/react-svg-worldmap#68]
**Is your feature request related to a problem? Please describe.**
Currently width is set to a fixed amount (ie: sm, lg, xl, xxl).  Another option to allow the svg to scale responsively to the width of the container would improve the UX compatibility for desktop/mobile screens.

**Describe the solution you'd like**
Add `responsive` option for `size` property to allow the `svg` to scale dynamically with the width of the container.

**Comment by yanivam** [comment]
This is a great idea and I have been thinking about this for a long time. I have been getting requests over email asking me for different sizes and have been thinking about this and I think this would be a great solution. Will begin working on it and send you an update.

**Comment by yanivam** [comment]
Hey @peetss!

Thank you so much for the suggestion! Check out https://github.com/yanivam/react-svg-worldmap/pull/70. Version 1.0.41 contains the string "responsive" as on option for size.

Thanks again,
Yams
