### ISSUE TITLE
[BUG] Russia is selected twice

### ISSUE THREAD

**Issue by erikpetersen-wf** [yanivam/react-svg-worldmap#71]
**Describe the bug**
Russia is counted as two countries, as evidenced by 
![russia2](https://user-images.githubusercontent.com/3472246/106362305-0d50bc00-62f0-11eb-9d1f-7f2d92e338dc.gif).

**To Reproduce**
1. Add `const data = [{ country: "ru", value: 141944641 }]` to data used for the map.
2. Notice how Russia counts as two countries.

**Expected behavior**
Russia should only be one country when it is hovered over.

**Comment by yanivam** [comment]
Good catch, the problem is with the highlighting boolean since the data is passed correctly for the tooltip. Will look into it thank you so much for the find! I really appreciate it.

Yams

**Comment by yanivam** [comment]
Issue fixed, had to do with marker functionality but since that is rarely used I decided to remove it and rethink it. Should be all set now, let me know if you find more bugs!

Thanks,
Yams
