### ISSUE TITLE
[ENHANCEMENT] Zoom

### ISSUE THREAD

**Issue by peetss** [yanivam/react-svg-worldmap#72]
**Describe the solution you'd like**
The world map is great, it would make for a better user interface if you could,
1) On a desktop, use mouse-wheel to zoom in/out on the map.
2) On a mobile, use double-click to zoom in on the map.

Have you ever thought about this, do you know how it could be done?

**Comment by yanivam** [comment]
Hey @peetss,

Sorry for not commenting earlier I saw this and have been thinking about it. I think there is a way to change the scale in the svg to "zoom" in on a specific country, however, I do not know if the scroll action works well on svgs, I will have to play around with it to see. I have added zooming to my backlog and will keep you posted. If you want more info about progress, you can always shoot me an email at yanivam123@gmail.com.

Thanks,
Yams

**Comment by yanivam** [comment]
Hey, I have decided that this is not in the scope of this project
