### ISSUE TITLE
Cannot find module 'react-path-tooltip' from '.../react-svg-worldmap/dist/WorldMap.js'

### ISSUE THREAD

**Issue by kaikilian** [yanivam/react-svg-worldmap#81]
Hi, we are having problems using the WorldMap in our test-suite. We are using the WorldMap in our StoryBook which is working great without any problems, but when we start a test-run the package has problems to load or find the module called 'react-path-tooltip'.

* "@testing-library/jest-dom": "^5.11.4"
* "react": "^17.0.1"
* "react-svg-worldmap": "^1.0.44"
* "@storybook/react": "^6.1.15"

This is our test:

```
import React from 'react'
import '@testing-library/jest-dom/extend-expect'
import { render, waitFor } from '@testing-library/react'
import { ThemeProvider } from 'styled-components'
import theme from '../../../../utils/theme'
import '../../../matchMedia.mock'
import { Default } from './MapChart.stories'

const renderComponent = ({ t }) =>
  render(
    <ThemeProvider theme={t}>
      <Default {...Default.args} />
    </ThemeProvider>
  )

test.skip('renders the MapChart in the primary state', async () => {
  // Render new instance in every test to prevent leaking state
  renderComponent({ t: theme })
  await waitFor(() => expect(document.getElementsByTagName('svg').length).toEqual(1))
})
```

here is the stacktrace from the test-run:

```
 FAIL  src/stories/components/atoms/MapChart/MapChart.test.js
  ● Test suite failed to run

    Cannot find module 'react-path-tooltip' from 'node_modules/react-svg-worldmap/dist/WorldMap.js'

    Require stack:
      node_modules/react-svg-worldmap/dist/WorldMap.js
      node_modules/react-svg-worldmap/dist/index.js
      src/components/atoms/MapChart/MapChart.js
      src/components/atoms/MapChart/index.js
      src/stories/components/atoms/MapChart/MapChart.stories.js
      src/stories/components/atoms/MapChart/MapChart.test.js

      at Resolver.resolveModule (node_modules/jest-runtime/node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/react-svg-worldmap/dist/WorldMap.js:1:259)
```

**Comment by yanivam** [comment]
Interesting! Thanks so much for the feedback. This seems to be an issue with the node_modules of the project, which to me indicates a problem with the importing of the tooltip in the dependencies. I will investigate the issue and come back to you.

Thanks again,
Yams

**Comment by yanivam** [comment]
Hey @kaikilian!
Thank you for the patience! You should see the newest version (1.1.0) up and it should include a fix for this issue, I will close this now for maintenance purposes but if you are having more trouble let me know and I will reopen the issue.
-Yaniv
