### ISSUE TITLE
[ENHANCEMENT] Add custom text labels to the map

### ISSUE THREAD

**Issue by code-scavenger-007** [yanivam/react-svg-worldmap#84]
Hey,

Can we modify other countries background color(not the entire map's background) apart from the one we are getting in data property. And is it possible to add name of the oceans in map. 

Thanks.

**Comment by yanivam** [comment]
Hey @code-scavenger-007,
Thanks for checking out my map and for the suggestions! For the ocean labels, that is a pretty straightforward feature. I can add a boolean called enable-ocean-labels or something for you to use. 

As for changing the color of the map, I see 2 options: either 1, use the current customStylingFunction to essentially tell the map which countries you want to change color (I can help with that implementation if you want, kind of hacky) or I can make another custom function for you where you can pass a list of countries for keys and colors for values and I can make the background based off of those if you want, that might just take me a but more time.

Thanks,
Yams

**Comment by Josh-Cena** [comment]
Hi, I've solved part of the issue: the style function is now applied to every country, whether highlighted or not. It's now the user's responsibility to handle the two cases with different logic if they want.

For the ocean labels, I'm thinking about a more generic `createMarkup` API which you can pass coordinates and labels to draw your own text labels on the map.
