### ISSUE TITLE
[BUG] Doesn't work with Next.js

### ISSUE THREAD

**Issue by jschuur** [yanivam/react-svg-worldmap#97]
If I try and use this in a brand new Next.js (11) app, I get a rendering error:

```
Server Error
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

Steps to reproduce:

1. Create brand new Next.js app: `npx create-next-app react-svg-worldmap-test`
2. Install react-svg-worldmap
3. Add `pages\map.js`:

```
import WorldMap from 'react-svg-worldmap';

export default function Map() {
  const data = [
    { country: 'cn', value: 1389618778 }, // china
    { country: 'in', value: 1311559204 }, // india
    { country: 'us', value: 331883986 }, // united states
    { country: 'id', value: 264935824 }, // indonesia
    { country: 'pk', value: 210797836 }, // pakistan
    { country: 'br', value: 210301591 }, // brazil
    { country: 'ng', value: 208679114 }, // nigeria
    { country: 'bd', value: 161062905 }, // bangladesh
    { country: 'ru', value: 141944641 }, // russia
    { country: 'mx', value: 127318112 }, // mexico
  ];

  return (
    <div className='App'>
      <WorldMap
        color='red'
        title='Top 10 Populous Countries'
        value-suffix='people'
        size='lg'
        data={data}
      />
    </div>
  );
}
```

4. Start dev server and visit http://localhost:3000/map

Versions:

```
    "next": "11.1.2",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-svg-worldmap": "^1.1.0"
```

**Comment by Josh-Cena** [comment]
Hello, Next.js uses SSR, and I did address this issue in #91. However the owner hasn't released a new version yet.

Meanwhile, you need to make this component BrowerOnly.

**Comment by Josh-Cena** [comment]
Your JSX is wrong:

```jsx
    <WorldMap
        color='red'
        title='Top 10 Populous Countries'
        valueSuffix='people'
        size='lg'
        data={data}
      />
```

This should work; if it still doesn't, it may be because of SSR (which won't happen in dev because dev is CSR, you can try building your site). I did address that in #91 but the owner hasn't released a new version. So you may have to wrap it in BrowserOnly.

**Comment by jschuur** [comment]
Thanks for the quick reply, @Josh-Cena! The problem was indeed that I wasn't using a named import.

I had the valueSuffix prop correct in my main app, just hadn't fixed it in the boiled down sample that I pasted here.

Super happy that I can keep coding away thanks to your help! 😃

**Comment by Josh-Cena** [comment]
Welcome :D It's okay to close this?
